-- Create a test table in production database
USE DATABASE PRODUCTION_DB;
USE SCHEMA PUBLIC;

CREATE TABLE IF NOT EXISTS CICD_TEST (
    ID INT,
    MESSAGE STRING,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
